version: "3.9"
services:
  app:
    build:
      context: .
      dockerfile: app.Dockerfile
    ports:
      - "8000:8000"
    networks:
      - backend
  fileserver:
    build:
      context: .
      dockerfile: fileserver.Dockerfile
    ports:
      - "5000:5000"
    networks:
      - backend
networks:
  backend:
    name: backend