version: "3.9"
services:
  app:
    build:
      context: .
      dockerfile: app.Dockerfile
    ports:
      - "8000:8000"
    volumes:
      - type: bind
        source: ./public
        target: /app/public
    networks:
      - backend
networks:
  backend:
    name: backend